[tool.poetry]
name = "flowp"
version = "0.1.0"
description = ""
authors = ["BracketJohn"]

[tool.poetry.dependencies]
python = "3.6.5"
numpy = "^1.15"
scipy = "^1.1"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
